# Generated by Django 2.2 on 2021-08-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NULL', max_length=200, unique=True)),
                ('name', models.CharField(default='NULL', max_length=200)),
                ('email', models.EmailField(default='NULL', max_length=200, unique=True)),
                ('password', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=200)),
                ('gender', models.CharField(default='NULL', max_length=200)),
                ('description', models.CharField(default='NULL', max_length=200)),
                ('category', models.CharField(default='NULL', max_length=200)),
                ('breed', models.CharField(default='NULL', max_length=200)),
                ('profile_pet', models.URLField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.UserInfo')),
            ],
        ),
    ]
