# Generated by Django 2.2 on 2021-08-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_breedinfo_categoryinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedinfo',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryInfo',
        ),
        migrations.RemoveField(
            model_name='petinfo',
            name='owner',
        ),
        migrations.DeleteModel(
            name='BreedInfo',
        ),
        migrations.DeleteModel(
            name='PetInfo',
        ),
    ]
