# Generated by Django 2.2 on 2021-08-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0003_auto_20210826_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=200)),
                ('gender', models.CharField(default='NULL', max_length=200)),
                ('description', models.CharField(default='NULL', max_length=200)),
                ('category', models.CharField(default='NULL', max_length=200)),
                ('breed', models.CharField(default='NULL', max_length=200)),
                ('profile_pet', models.URLField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='BreedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(default='NULL', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.UserInfo')),
            ],
        ),
    ]
