# Generated by Django 2.2 on 2021-08-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0002_auto_20210827_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
