# Generated by Django 2.2 on 2021-08-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0003_auto_20210827_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
