# Generated by Django 2.2 on 2021-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0004_auto_20210827_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
