# Generated by Django 2.2 on 2021-08-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0005_auto_20210827_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petinfo',
            old_name='id',
            new_name='pet_id',
        ),
    ]
