# Generated by Django 2.2 on 2021-08-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0007_auto_20210827_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='petinfo',
            name='identifier',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
