# Generated by Django 2.2 on 2021-08-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0008_petinfo_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='identifier',
            field=models.TextField(default='NULL', max_length=200),
        ),
    ]
