# Generated by Django 2.2 on 2021-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0009_auto_20210827_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='identifier',
            field=models.TextField(),
        ),
    ]
