# Generated by Django 2.2 on 2021-08-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0010_auto_20210827_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedinfo',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryInfo',
        ),
        migrations.DeleteModel(
            name='BreedInfo',
        ),
    ]
